import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  booleanAttribute,
  computed,
  effect,
  input,
  signal,
  viewChild,
} from '@angular/core';
import { IMAGE_MANIFEST, type ImageMeta } from '../../../core/data/image-manifest';

/**
 * The one image element the app uses.
 *
 * Given the original asset path it looks up `IMAGE_MANIFEST` (generated by
 * `npm run images:optimize`) and emits:
 *   - a WebP `srcset` covering every variant that exists on disk,
 *   - intrinsic `width`/`height` so the box is reserved before load (no CLS),
 *   - `loading="lazy"` + `decoding="async"` by default, or eager +
 *     `fetchpriority="high"` for the one above-the-fold LCP image.
 *
 * Pass `placeholder` with a URL that is *already in the browser cache* (e.g. the
 * thumbnail the user just clicked) and it paints instantly, slightly blurred,
 * while the full-resolution variant downloads in the background — then swaps
 * with no flash. That is what makes the gallery lightbox open immediately.
 *
 * Unknown paths (SVGs, remote URLs) degrade to a plain `<img>`, so it is safe
 * to use everywhere.
 *
 * Usage:
 *   <app-img src="assets/images/hero/hero-event.jpeg" alt="…" priority
 *            sizes="(min-width: 1024px) 40vw, 90vw"
 *            imgClass="h-full w-full object-cover" />
 */
@Component({
  selector: 'app-img',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <picture>
      @if (srcset(); as set) {
        @if (!showingPlaceholder()) {
          <source type="image/webp" [attr.srcset]="set" [attr.sizes]="sizes()" />
        }
      }
      <img
        #img
        [src]="showingPlaceholder() ? placeholder() : src()"
        [alt]="alt()"
        [attr.width]="meta()?.width ?? null"
        [attr.height]="meta()?.height ?? null"
        [attr.loading]="priority() || eager() ? 'eager' : 'lazy'"
        [attr.fetchpriority]="priority() ? 'high' : null"
        [attr.decoding]="priority() ? 'sync' : 'async'"
        [class]="imgClass()"
        [class.app-img--upgrading]="showingPlaceholder()"
      />
    </picture>
  `,
  styles: [
    `
      /* Participate in the parent's layout exactly as a bare <img> would. */
      :host,
      picture {
        display: contents;
      }

      /* Masks the softness of an upscaled placeholder, and makes the swap to
         full resolution read as a deliberate progressive load. */
      .app-img--upgrading {
        filter: blur(8px);
      }

      img {
        transition: filter 320ms ease-out;
      }

      @media (prefers-reduced-motion: reduce) {
        img {
          transition: none;
        }
      }
    `,
  ],
})
export class ImgComponent {
  /** Original asset path, e.g. `assets/images/gallery/photos/photo-01.jpeg`. */
  readonly src = input.required<string>();
  readonly alt = input.required<string>();
  /** `sizes` hint so the browser picks the right variant before layout. */
  readonly sizes = input<string>('100vw');
  /** Mark the above-the-fold LCP image — loads eagerly at high priority. */
  readonly priority = input(false, { transform: booleanAttribute });
  /**
   * Load immediately but at normal priority. Use for images that start in the
   * viewport without being the LCP element (the gallery's first row): native
   * lazy loading defers those until after layout, which makes them appear
   * *later* than if they had never been marked lazy at all.
   */
  readonly eager = input(false, { transform: booleanAttribute });
  /** Classes applied to the inner `<img>` (the element that is laid out). */
  readonly imgClass = input<string>('');
  /**
   * An already-cached URL to paint immediately while the real variant loads.
   * Only pass a URL you know the browser has (e.g. an on-screen thumbnail's
   * `currentSrc`) — otherwise it is just an extra request.
   */
  readonly placeholder = input<string | null>(null);

  private readonly imgRef = viewChild<ElementRef<HTMLImageElement>>('img');
  /** Set once the full-resolution variant has finished downloading. */
  private readonly upgraded = signal(false);

  protected readonly meta = computed<ImageMeta | null>(() => IMAGE_MANIFEST[this.src()] ?? null);

  protected readonly srcset = computed(() => buildSrcset(this.src()));

  protected readonly showingPlaceholder = computed(
    () => !!this.placeholder() && !this.upgraded(),
  );

  constructor() {
    // Whenever we are showing a placeholder, warm the real variant in the
    // background and swap the moment it is decodable — the swap then comes
    // straight from cache, so there is no flash of empty space.
    effect((onCleanup) => {
      const placeholder = this.placeholder();
      const src = this.src();
      const sizes = this.sizes();
      const srcset = buildSrcset(src);

      this.upgraded.set(false);
      if (!placeholder || typeof Image === 'undefined') {
        this.upgraded.set(true);
        return;
      }

      const warm = new Image();
      // Setting sizes before srcset makes the browser pick the same candidate
      // the <picture> element will settle on.
      warm.sizes = sizes;
      if (srcset) warm.srcset = srcset;
      warm.src = src;

      let cancelled = false;
      const done = () => {
        if (!cancelled) this.upgraded.set(true);
      };
      if (warm.complete) done();
      else {
        warm.addEventListener('load', done, { once: true });
        warm.addEventListener('error', done, { once: true });
      }

      onCleanup(() => {
        cancelled = true;
        warm.removeEventListener('load', done);
        warm.removeEventListener('error', done);
      });
    });
  }

  /**
   * The variant the browser actually chose. Useful as the `placeholder` for a
   * larger rendering of the same image (the lightbox), since it is guaranteed
   * to be in cache.
   */
  currentSrc(): string {
    return this.imgRef()?.nativeElement.currentSrc || this.src();
  }
}

/**
 * WebP `srcset` for an asset path, or null when the path is not a managed
 * raster image (SVGs, remote URLs).
 */
export function buildSrcset(src: string): string | null {
  const meta = IMAGE_MANIFEST[src];
  if (!meta) return null;
  const base = src.replace(/\.(jpe?g|png)$/i, '');
  return meta.widths.map((w) => `${base}-${w}.webp ${w}w`).join(', ');
}

/**
 * Warm the browser cache with the variant a future render will pick. Used to
 * prefetch a gallery image at lightbox resolution on hover.
 */
export function prefetchVariant(src: string, sizes: string): void {
  if (typeof Image === 'undefined') return;
  const srcset = buildSrcset(src);
  const img = new Image();
  img.sizes = sizes;
  if (srcset) img.srcset = srcset;
  img.src = src;
}
